### ISSUE TITLE
Setup build framework

### ISSUE THREAD

**Issue by gelencser09** [BME-MIT-IET/iet-hf-2023-test-and-rest#2]
Maven / Gradle

**Comment by zotya0601** [comment]
Első commit során, mikor ténylegesen hozzáadtam a `pom.xml` fájlt, elfelejtettem a `Closes #2` azonosítót használni. 

A `maven_buildsys` branch tartalmazza a Maven buildrendszerhez szükséges `pom.xml` fájlt, melyet úgy konfiguráltam, hogy lehetőleg ne kelljen fájlokat mozgatni (létezik egy, a Maven által preferált struktúra).

Mindeközben találtam egy hibát, melytől a grafikai elemek nem jelentek meg mindig a felületen. Ezt nem itt kellett volna javítsam, mivel ez egy, az Issue-n túlmutató probléma, a javítást kiveszem és hozok létre neki egy új Issue-t, amennyiben szükséges.
