### ISSUE TITLE
Document manual UI tests

### ISSUE THREAD

**Issue by gelencser09** [BME-MIT-IET/iet-hf-2023-test-and-rest#5]

**Comment by BAndriss** [comment]
Lásd: [https://github.com/BME-MIT-IET/iet-hf-2023-test-and-rest/wiki/Documentation#manu%C3%A1lis-tesztek](https://github.com/BME-MIT-IET/iet-hf-2023-test-and-rest/wiki/Documentation#manu%C3%A1lis-tesztek)
